version: "3.8"

services:
  api:
    image: python:3.11
    container_name: fastapi_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
